version: '2.3'
services:
  postgres:
    image: postgres:9.6
    environment:
        - "POSTGRES_PASSWORD=${B2SHARE_POSTGRESQL_PASSWORD}"
        - "POSTGRES_USER=${B2SHARE_POSTGRESQL_USER}"
        - "POSTGRES_DB=${B2SHARE_POSTGRESQL_DBNAME}"
        - "PGDATA=/var/lib/postgresql/data"
    volumes:
        - "${B2SHARE_DATADIR}/postgres-data:/var/lib/postgresql/data"
    expose:
        - "5432"

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    hostname: elasticsearch
    expose:
      - "9200"
      - "9300"
    volumes:
      - "${B2SHARE_DATADIR}/elasticsearch:/usr/share/elasticsearch/data"

  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  mq:
    image: rabbitmq:3.8-management-alpine
    restart: "always"
    environment:
      - "RABBITMQ_DEFAULT_USER=${B2SHARE_RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${B2SHARE_RABBITMQ_PASS}"
    expose:
      - "15672"
      - "5672"
    volumes:
        - "${B2SHARE_DATADIR}/rabbitmq-data:/var/lib/rabbitmq"

  b2share:
    build:
      context: .
      dockerfile: Dockerfile.b2share
    env_file:
      - .env
    environment:
      - "B2SHARE_SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://${B2SHARE_POSTGRESQL_USER}:${B2SHARE_POSTGRESQL_PASSWORD}@postgres:5432/${B2SHARE_POSTGRESQL_DBNAME}'"
      - "B2SHARE_CACHE_REDIS_HOST='redis'"
      - "B2SHARE_CACHE_REDIS_URL='redis://redis:6379/0'"
      - "B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://redis:6379/1'"
      - "B2SHARE_BROKER_URL='amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@mq:5672/'"
      - "B2SHARE_CELERY_BROKER_URL='amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@mq:5672/'"
    volumes:
      - ".:/build"
      - "${B2SHARE_SOURCE}:/eudat/b2share"
      - "${B2SHARE_DATADIR}/b2share:/usr/var/b2share-instance"
    expose:
      - "5000"
    links:
      - elasticsearch
      - redis
      - postgres
      - mq

  nginx:
    build: nginx
    ports:
      - "80:80/tcp"
    links:
      - b2share
