version: '2'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - "./instance/postgres:/var/lib/postgresql/data"
    hostname: db
    ports:
      - "127.0.0.1:5432:5432"

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    hostname: elasticsearch
    expose:
      - "9200"
      - "9300"
    volumes:
      - "./instance/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    links:
      - postgres


  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
    ports:
      - "127.0.0.1:6379:6379"

  mq:
    hostname: b2share-redis
    image: rabbitmq:3.6-management-alpine
    restart: "always"
    environment:
      - "RABBITMQ_DEFAULT_USER=b2share"
      - "RABBITMQ_DEFAULT_PASS=b2share"
    expose:
      - "15672"
      - "5672"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

  b2share:
    #image: eudatb2share/b2share:2.1.4
    build:
      context: .
      dockerfile: Dockerfile.b2share
    env_file:
      - .env
    environment:
      - "B2SHARE_SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://${B2SHARE_POSTGRESQL_USER}:${B2SHARE_POSTGRESQL_PASSWORD}@postgres:5432/${B2SHARE_POSTGRESQL_DBNAME}'"
      - "B2SHARE_CACHE_REDIS_HOST='redis'"
      - "B2SHARE_CACHE_REDIS_URL='redis://redis:6379/0'"
      - "B2SHARE_ACCOUNTS_SESSION_REDIS_URL='redis://redis:6379/1'"
      - "B2SHARE_BROKER_URL='amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@mq:5672/'"
      - "B2SHARE_CELERY_BROKER_URL='amqp://${B2SHARE_RABBITMQ_USER}:${B2SHARE_RABBITMQ_PASS}@mq:5672/'"
    volumes:
      - ".:/build"
      - "$B2SHARE:/build/b2share"
      - "./instance:/usr/var/b2share-instance"
    expose:
      - "5000"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:1984:1984"
    links:
      - elasticsearch
      - redis
      - postgres
